name: Build and Deploy GreenScreenFrontend App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # IMPROVEMENT: Explicitly set up the Node.js version for consistency
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or whatever version your project requires
          cache: 'pnpm' # Caches dependencies for faster builds

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify pnpm version

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: |
          pnpm build
          pnpm generate

      - name: Deploy with rsync
        run: |
          # This step requires the runner user to have passwordless sudo permissions for mkdir and rsync
          sudo mkdir -p /var/www/greenscreen.chrixel.com
          sudo rsync -av --delete .output/public/ /var/www/greenscreen.chrixel.com/
